"""Generate the worked job plans and table from the supplied scenarios.

Results are written to job_example/results/. All live facts are authored inputs,
and nothing is sent to a robot. Run: python3 -B job_example/run_example.py"""
import json
import re
import sys
from pathlib import Path

sys.dont_write_bytecode = True
HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
from job_plan import plan, load_catalogue      # noqa: E402

SHORT = {'RECOMMENDED': 'recommended (offline; no dispatch)', 'PENDING_CONFIRMATION': 'pending confirmation',
         'PENDING_CHOICE': 'pending owner choice', 'WAITING': 'waiting (platform busy)',
         'WAITING_FOR_PERSON': 'waiting for a qualified person', 'MANUAL_ASSIGNED': 'manual alternative assigned',
         'CONDITIONAL_ON_INPUT': 'conditional on input', 'BLOCKED_INPUT': 'blocked: input unobtainable',
         'BLOCKED_SHARED': 'blocked: shared condition failed', 'WITHHELD_SHARED': 'withheld: shared condition unknown',
         'BLOCKED_EVIDENCE': 'blocked: no supporting record', 'BLOCKED_TASK_CONDITION': 'blocked: local task condition failed',
         'BLOCKED_NOT_IN_TEAM': 'blocked: supporting robot not in the team',
         'WITHHELD_TASK_CONDITION': 'withheld: local task condition unknown', 'BLOCKED_ROBOT_CHECK': 'blocked: robot check failed',
         'WITHHELD_ROBOT_CHECK': 'withheld: robot facts unresolved'}


def gap_text(row):
    if not row['gap']:
        return ''
    fields = sorted({f for g in row['gap'] for f in g['mismatch']})
    return 'records differ in ' + ', '.join(fields)


def assigned(row):
    parts = []
    if row['robot']:
        r = row['robot']
        parts.append('%s (%s%s)' % (r['platform'], r['configuration'], ', %g N' % r['setpoint_n'] if r['setpoint_n'] else ''))
    if row['person']:
        parts.append('%s as %s' % (row['person'], '/'.join(row['person_role'])))
    return '; '.join(parts) or '–'


def note(row):
    bits = []
    if row['selector']:
        s = row['selector']
        bits.append('selector %s' % s['decision'] + (' (%s)' % ', '.join(s['remaining']) if s['decision'] == 'ASK' else ''))
    if row['inputs']:
        bits.append('needs %s from %s (%s)' % (row['inputs'][0]['output'], row['inputs'][0]['from'], row['inputs'][0]['status']))
    g = gap_text(row)
    if g:
        bits.append(g)
    if row.get('outside_team'):
        bits.append('record only for %s, outside the declared team' % ', '.join(sorted({e['platform'] for e in row['outside_team']})))
    if row.get('manual_alternative') and not row['manual_alternative']['original_request_fulfilled']:
        bits.append('regulated request not fulfilled')
    if row.get('reasons'):
        bits.append('unresolved or failed: ' + ', '.join(row['reasons']))
    if row['synthetic']:
        bits.append('synthetic: ' + ', '.join(row['synthetic']))
    return '; '.join(bits)


def table(result):
    groups = []
    for row in result['tasks']:
        key = (SHORT[row['state']], assigned(row) if not row['person'] or not row.get('manual_alternative') else 'person',
               re.sub(r'from \S+ \(', 'from its locate task (', note(row)))
        for g in groups:
            if g['key'] == key and g['label_stem'] == row['label'].rstrip('0123456789 '):
                g['ids'].append(row['id']); g['people'].append(row['person']); break
        else:
            groups.append({'key': key, 'ids': [row['id']], 'label_stem': row['label'].rstrip('0123456789 '),
                           'people': [row['person']], 'row': row})
    lines = []
    for g in groups:
        row = g['row']
        who = assigned(row) if not row.get('manual_alternative') else \
            '; '.join('%s: %s' % (i, p) for i, p in zip(g['ids'], g['people']))
        label = row['label'] if len(g['ids']) == 1 else '%s (%d tasks: %s)' % (g['label_stem'], len(g['ids']), ', '.join(g['ids']))
        lines.append('| %s | %s | %s | %s |' % (label, SHORT[row['state']], who, note(row) if len(g['ids']) == 1 else g['key'][2]))
    return lines


def main():
    catalogue = load_catalogue()
    out = HERE / 'results'; out.mkdir(exist_ok=True)
    runs = {}
    building = json.loads((HERE / 'scenarios/customer_building.json').read_text())
    tested = json.loads((HERE / 'scenarios/tested_contexts.json').read_text())
    runs['customer_building'] = plan(building, catalogue)
    runs['tested_contexts'] = plan(tested, catalogue)
    runs['tested_contexts_with_synthetic_declarations'] = plan(tested, catalogue, declarations=tested['synthetic_declarations'])
    for name, result in runs.items():
        (out / ('PLAN_%s.json' % name)).write_text(json.dumps(result, indent=2, sort_keys=True) + '\n')
    md = ['# Worked example: generated job plans', '',
          'Generated by job_example/run_example.py from actual calls to the unchanged selector and the authored scenarios in '
          'job_example/scenarios/. Live facts are synthetic; slots are logical labels without durations; nothing is dispatched.', '']
    for name, title in (('customer_building', 'Customer building (physical requests in new contexts)'),
                        ('tested_contexts', 'Tested contexts, before any declaration (each case judged in its own context)'),
                        ('tested_contexts_with_synthetic_declarations', 'Tested contexts, after synthetic owner choice and confirmations')):
        r = runs[name]
        md += ['## ' + title, '', '| Task(s) | Plan state | Assigned (robot configuration; person and role) | Selector outcome and notes |',
               '|---|---|---|---|'] + table(r)
        md += ['', 'Human actions required: ' + ('; '.join('%s — %s%s' % (a['task'], a['action'], ' (%s)' % a['by'] if a['by'] else '')
                                                        for a in r['human_actions']) or 'none'),
               'Declared work requirement (not converted to time, cost or fleet size): ' +
               ', '.join('%s: %s' % (k.replace('_', ' '), v) for k, v in r['declared_tally'].items()),
               'Selector calls: %d.' % r['selector_calls'] + (' Scope queries (decision discarded): %d.' % r['scope_queries']
                                                              if r['scope_queries'] else ''), '']
    (out / 'JOB_PLAN_TABLE.md').write_text('\n'.join(md))
    print('\n'.join(md))


if __name__ == '__main__':
    main()
